### ISSUE TITLE
Crash - 'Enemy' object has no attribute 'good_statuses'

### ISSUE THREAD

**Issue by mooneroid** [dcripplinger/rotj#2]
This happened in a battle, when I was showing my kids the game progress.  I think I chose 'Risk-it' against 4 or 5 Amlicites, and it crashed right then.
I'm not sure what the intent of `BattleWarlordRectBase.bad_statuses` is, or if it should also include a `good_statuses`, so I didn't fix it.  
```
Traceback (most recent call last):
  File "/Users/justinmoon/rotj/src/rotj.py", line 19, in <module>
    game.run()
  File "/Users/justinmoon/rotj/src/game.py", line 725, in run
    self.update(dt)
  File "/Users/justinmoon/rotj/src/game.py", line 545, in update
    self.battle.update(dt)
  File "/Users/justinmoon/rotj/src/battle.py", line 278, in update
    self.update_risk_it(dt)
  File "/Users/justinmoon/rotj/src/battle.py", line 212, in update_risk_it
    self.simulate_battle()
  File "/Users/justinmoon/rotj/src/battle.py", line 522, in simulate_battle
    self.simulate_volley()
  File "/Users/justinmoon/rotj/src/battle.py", line 537, in simulate_volley
    self.submit_ai_moves()
  File "/Users/justinmoon/rotj/src/battle.py", line 533, in submit_ai_moves
    self.generate_enemy_moves()
  File "/Users/justinmoon/rotj/src/battle.py", line 782, in generate_enemy_moves
    self.enemy_moves.append(self.generate_enemy_move(enemy, ally_target_index, sum_dangers))
  File "/Users/justinmoon/rotj/src/battle.py", line 862, in generate_enemy_move
    (boost_tactic == 'hulk~out' or boost_tactic not in random_enemy.good_statuses)
AttributeError: 'Enemy' object has no attribute 'good_statuses'
```

**Comment by dcripplinger** [comment]
I believe this was fixed somewhat recently. `good_statuses` exists now.
