### ISSUE TITLE
Crash in battle when I chose "Item" on Alma

### ISSUE THREAD

**Issue by mooneroid** [dcripplinger/rotj#9]
Just keeping track of this one.  Haven't dug in yet.
I went into a battle without equipping anything on Alma, so I went to look at his items during the battle, and got this crash.  

Traceback (most recent call last):
  File "/Users/jmoon/rotj/src/rotj.py", line 19, in <module>
    game.run()
  File "/Users/jmoon/rotj/src/game.py", line 819, in run
    self.handle_input()
  File "/Users/jmoon/rotj/src/game.py", line 792, in handle_input
    self.battle.handle_input(pressed)
  File "/Users/jmoon/rotj/src/battle.py", line 1177, in handle_input
    self.handle_input_menu(pressed)
  File "/Users/jmoon/rotj/src/battle.py", line 1097, in handle_input_menu
    self.handle_item()
  File "/Users/jmoon/rotj/src/battle.py", line 1127, in handle_item
    self.menu = self.warlord.get_item_menu()
  File "/Users/jmoon/rotj/src/battle_warlord_rect.py", line 113, in get_item_menu
    return MenuGrid([column1, column2], border=True)
  File "/Users/jmoon/rotj/src/text.py", line 414, in __init__
    self.set_focused_menu(self.focused_menu_index)
  File "/Users/jmoon/rotj/src/text.py", line 437, in set_focused_menu
    self.focused_menu.set_choice(inner_choice)
  File "/Users/jmoon/rotj/src/text.py", line 350, in set_choice
    assert 0 <= index < len(self.choices)
AssertionError

**Comment by mooneroid** [comment]
Looking this one over again, I think Alma was carrying no items, so that assertion failed because when it says `index < len(self.choices)` it's saying `0 < 0` in that case.
